version: "3.8"

services:
  tr-docs-user:
    build:
      dockerfile: Dockerfile.user
    image: tr-docs-user:${VERSION:-latest}
    container_name: tr-docs-user
    ports:
      - "4001:4001"
    environment:
      - NODE_ENV=production

  tr-docs-maintainer:
    build:
      dockerfile: Dockerfile.maintainer
    image: tr-docs-maintainer:${VERSION:-latest}
    container_name: tr-docs-maintainer
    ports:
      - "4002:4002"
    environment:
      - NODE_ENV=production
